var fs=require('fs')
var data=fs.readFileSync('pr4_1_value.txt')
data =data.toString().split('\n')
n1=parseInt(data[0])
n2=parseInt(data[1])
console.log("addition: "+(n1+n2))
console.log("subtraction: "+(n1-n2))
console.log("division: "+(n1/n2))
console.log("multiplication: "+(n1*n2))